name: timely
description: "A new Flutter project."
publish_to: "none"

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  google_fonts: ^6.3.1
  intl: ^0.20.2
  geolocator: ^14.0.2
  image_picker: ^1.2.0
  lottie: ^3.3.2
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.8
  google_maps_flutter: ^2.13.1
  geocoding: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  logger: ^2.5.0
  package_info_plus: ^8.3.1
  sticky_headers: ^0.2.0
  syncfusion_flutter_charts: ^31.1.20
  printing: ^5.10.0
  pdf: ^3.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo1.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/translations/en.json
    - assets/translations/id.json
    - assets/images/homeoff.png
    - assets/images/homeon.png
    - assets/images/useroff.png
    - assets/images/useron.png
    - assets/images/avatar.png
    - assets/images/charton.png
    - assets/images/chartoff.png
    - assets/images/historyon.png
    - assets/images/historyoff.png
    - assets/images/3.png
    - assets/images/splashscreen.json
    - assets/images/logo2.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
